name: Create Release

on:
  push:
    tags:
  workflow_dispatch:
  release:

jobs:
# Create XCFramework when a version is tagged
  xcframework:
    name: XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_12.app
           xcodebuild -version
           swift --version
      - name: Swift Version
        run: swift --version
      # Create a release
      - name: Build XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.3
      # Upload those artifacts to the release
      - name: Upload xcframework
        uses: actions/upload-artifact@v2
        with:
          name: xcframework
          path: Bluetooth.xcframework
          if-no-files-found: error
